package org.pinhead;

public enum Opcode {
    NONE, CLS, RET, JMP_IMM, CALL, SE_IMM, SNE_IMM, SE, SNE, LD_IMM, ADD_IMM, LD, OR, AND, XOR, ADD_CARRY, SUB_CARRY, SHR, SUB_NCARRY, SHL, LD_I, JMP, RND, DRW, SKP, SKNP, LD_DT, LD_K, ADD_I, LD_F, SET_DT, SET_ST, BCD, STORE, LOAD
}
